version: "2"
services:

  #SHARD 1
  mongors1n1:
    container_name: mongors1n1
    image: mongo:3.4
    command: mongod --shardsvr --replSet mongors1
    volumes:
      - mongors1n1vol:/data/db

  mongors1n2:
    container_name: mongors1n2
    image: mongo:3.4
    command: mongod --shardsvr --replSet mongors1
    volumes:
      - mongors1n2vol:/data/db

  mongors1n3:
    container_name: mongors1n3
    image: mongo:3.4
    command: mongod --shardsvr --replSet mongors1
    volumes:
      - mongors1n3vol:/data/db

  #SHARD 2
  mongors2n1:
    container_name: mongors2n1
    image: mongo:3.4
    command: mongod --shardsvr --replSet mongors2
    volumes:
      - mongors2n1vol:/data/db

  mongors2n2:
    container_name: mongors2n2
    image: mongo:3.4
    command: mongod --shardsvr --replSet mongors2
    volumes:
      - mongors2n2vol:/data/db

  mongors2n3:
    container_name: mongors2n3
    image: mongo:3.4
    command: mongod --shardsvr --replSet mongors2
    volumes:
      - mongors2n3vol:/data/db

  #CONFIG
  mongocfg1:
    container_name: mongocfg1
    image: mongo:3.4
    command: mongod --configsvr --replSet mongoconfg
    volumes:
      - mongocfg1vol:/data/db

  mongocfg2:
    container_name: mongocfg2
    image: mongo:3.4
    command: mongod --configsvr --replSet mongoconfg
    volumes:
      - mongocfg2vol:/data/db

  mongocfg3:
    container_name: mongocfg3
    image: mongo:3.4
    command: mongod --configsvr --replSet mongoconfg
    volumes:
      - mongocfg3vol:/data/db

  mongos1:
    container_name: mongos1
    image: mongo:3.4
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
    command: mongos --configdb mongoconfg/mongocfg1:27019,mongocfg2:27019,mongocfg3:27019
#    ports:
#      - 27017:27017
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - .:/tmp
#
  mongos2:
    container_name: mongos2
    image: mongo:3.0.14
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
    command: mongos --configdb mongoconfg/mongocfg1:27019,mongocfg2:27019,mongocfg3:27019
#    ports:
#      - 27018:27017
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - .:/tmp

volumes:
  mongors1n1vol:
  mongors1n2vol:
  mongors1n3vol:
  mongors2n1vol:
  mongors2n2vol:
  mongors2n3vol:
  mongocfg1vol:
  mongocfg2vol:
  mongocfg3vol: